# Generated by Django 4.1.4 on 2022-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='remember',
            unique_together={('latitude', 'longitude')},
        ),
    ]
